:project_name: SimpleTooltip
= {project_name}

image:https://github.com/gesinn-it-pub/SimpleTooltip/actions/workflows/ci.yml/badge.svg[CI,link=https://github.com/gesinn-it-pub/SimpleTooltip/actions/workflows/ci.yml]
image:https://codecov.io/github/gesinn-it-pub/SimpleTooltip/graph/badge.svg?token=hmfXuxLJC8[Codecov]

{project_name} is a MediaWiki extension that provides basic tooltips, supporting inline text and info icons

== Documentation
For documentation see: https://www.mediawiki.org/wiki/Extension:SimpleTooltip

== Versioning

We use http://semver.org/[SemVer] for versioning. See the tags in this repository for  available versions.

== Contributing
We welcome contributions from the community to help make {project_name} better! Whether you're fixing bugs, adding new features, improving documentation, or anything else, your efforts are valuable.

We try to follow the https://www.conventionalcommits.org/[Conventional Commits specification] for issues and commit messages to create good and meaningful change logs.

For detailed information, see our link:++contributing guidelines.adoc++[Contributing Guidelines].

== Attribution
Uses the http://iamceege.github.io/tooltipster/[Tooltipster Library] and https://github.com/yusukekamiyamane/fugue-icons[Fugue Icons]

---
This extension is part of https://semantic.wiki/core[*semantic::core*] - Enterprise Class MediaWiki distribution.
